name: Update
on:
  schedule:
    - cron: '0 0 1 * *'  # Run at midnight on first day of each month
  workflow_dispatch:      # Allow manual trigger

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      contents: write    # Needed for pushing changes
    steps:
      - uses: actions/checkout@v4
      
      - name: Install the latest version of uv and set the python version
        uses: astral-sh/setup-uv@v5
        with:
          python-version: 3.13
          
      - name: Install script and run
        run: |
          uv pip install -e ./dev --system
          uv python -m revlib-src-dev
          
      - name: Check for changes
        id: changes
        run: |
          git diff --quiet || echo "has_changes=true" >> $GITHUB_OUTPUT
          
      - name: Commit and push if changes
        if: steps.changes.outputs.has_changes == 'true'
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add .
          git commit -m "Monthly auto-update $(date +%Y-%m-%d)"
          git push